title: Cidney Hamilton
email: cidney@cidneyhamilton.com
description: "UX designer, developer, interactive fiction writer."
baseurl: "" 
url: "http://cidneyhamilton.com"
github_username:  cidneyhamilton
theme: minima
gem "github-pages", group: :jekyll_plugins
