title: Cidney Hamilton
email: cidney@cidneyhamilton.com
description: "Cidney Hamilton's personal website."

baseurl: "/" 
url: "http://cidneyhamilton.com"
github_username:  cidneyhamilton
mastodon_url: https://mastodon.gamedev.place/@cidney
facebook_url: https://www.facebook.com/cidney.hamilton

gem "github-pages", group: :jekyll_plugins

blog_title: "Dev Log"
blog_blurb: "500 words a day on whatever I want to write about."
microblog_title: "Notes"
microblog_blurb: "120 characters on whatever I want to write about. Mostly archived from Mastodon."

collections:
  notes:
    output: true
    permalink: microblog/:year/:month/:day/:title

