title: Cidney Hamilton
email: cidney@cidneyhamilton.com
description: "Cidney Hamilton's personal website."
author: Cidney Hamilton
url: "http://www.cidneyhamilton.com/"

github_username:  cidneyhamilton
mastodon_url: https://mastodon.gamedev.place/@cidney
facebook_url: https://www.facebook.com/cidney.hamilton
twitter_username: cidneyhamilton

micropub_url: "https://secure-lake-98955.herokuapp.com/micropub/main"
webmention_url: "https://webmention.io/www.cidneyhamilton.com/webmention"
pingback_url: "https://webmention.io/www.cidneyhamilton.com/xmlrpc"

blog_title: "Latest Updates"
microblog_title: "Notes"

webmentions:
  username: www.cidneyhamilton.com
  collections: 
    - notes


collections:
  notes:
    output: true
    permalink: microblog/:year/:month/:day/:title

